version: 0.1
phases:
  install:
    commands:
      - echo "install step"
      - pip install mkdocs
      - pip install mkdocs-material
      - pip install mkdocs-pdf-export-plugin
  pre_build:
    commands:
  build:
    commands:
      - echo "build step"
      - mkdocs build
      - aws s3 sync site s3://win319.reinvent-session.com
  post_build:
    commands:
